package com.kevin.live.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kevin.live.database.TrainHistoryEntity;
import com.kevin.live.database.TrainNoHistoryEntity;

import com.kevin.live.database.TrainHistoryEntityDao;
import com.kevin.live.database.TrainNoHistoryEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trainHistoryEntityDaoConfig;
    private final DaoConfig trainNoHistoryEntityDaoConfig;

    private final TrainHistoryEntityDao trainHistoryEntityDao;
    private final TrainNoHistoryEntityDao trainNoHistoryEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trainHistoryEntityDaoConfig = daoConfigMap.get(TrainHistoryEntityDao.class).clone();
        trainHistoryEntityDaoConfig.initIdentityScope(type);

        trainNoHistoryEntityDaoConfig = daoConfigMap.get(TrainNoHistoryEntityDao.class).clone();
        trainNoHistoryEntityDaoConfig.initIdentityScope(type);

        trainHistoryEntityDao = new TrainHistoryEntityDao(trainHistoryEntityDaoConfig, this);
        trainNoHistoryEntityDao = new TrainNoHistoryEntityDao(trainNoHistoryEntityDaoConfig, this);

        registerDao(TrainHistoryEntity.class, trainHistoryEntityDao);
        registerDao(TrainNoHistoryEntity.class, trainNoHistoryEntityDao);
    }
    
    public void clear() {
        trainHistoryEntityDaoConfig.clearIdentityScope();
        trainNoHistoryEntityDaoConfig.clearIdentityScope();
    }

    public TrainHistoryEntityDao getTrainHistoryEntityDao() {
        return trainHistoryEntityDao;
    }

    public TrainNoHistoryEntityDao getTrainNoHistoryEntityDao() {
        return trainNoHistoryEntityDao;
    }

}
